import nmap
ns = nmap.PortScanner()
print("===================")
print ("Welcome to bnmap")
print (ns.nmap_version())
print("===================")
ip=raw_input("Enter IP/Url: ")
ns.scan(ip,'1-1000','-v')
print("Scaning status: ")
print(ns.scanstats())
print("....")
print("current uphosts: ")
print(ns.all_hosts())
print("....")
#print(ns.scaninfo())
#print("....")
print("Port history of hosts are: ")
print(ns.csv())
print("....")